# -*- coding: utf-8 -*-
"""APIVcc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    # https://colab.research.google.com/drive/184BBiDfIRH98a6SIteOeOaNoR_H5tyne

## Phần 1
Xử lý dữ liệu đầu vào

###Load du lieu
"""

from pyvi import ViTokenizer # thư viện NLP tiếng Việt
import numpy as np
import gensim  # thư viện NLP

from sklearn.decomposition import TruncatedSVD
from flask import Flask
from flask import jsonify
import json
import pickle
# tfidf thường
path = open("/home/xa/Documents/XApython/codeVcc/classification/save_tfidf.pkl", 'rb')
tfidf_vect = pickle.load(path)

# tfidf_svd
svd = TruncatedSVD(n_components=300, random_state=42)
path = open("/home/xa/Documents/XApython/codeVcc/classification/save_X_data_tfidf.pkl", 'rb')
X_data_tfidf = pickle.load(path)
svd.fit(X_data_tfidf)

# model
import pickle
path = open("/home/xa/Documents/XApython/codeVcc/classification/save_mode_xgb_2.pkl", 'rb')
bst = pickle.load(path)

def xuLy(X_data_all):

    X_data_ok = np.array(X_data_all)
    X_data_ok.astype('str')
    X_data = []

    for line in X_data_ok:
        line = gensim.utils.simple_preprocess(line)
        line_1 = ' '.join(line)
        line_2 = ViTokenizer.tokenize(line_1)
        X_data.append(line_2)
    return X_data


def classify(content):
    X_test = [content]
    X_test = xuLy(X_test)
    global  X_test_tfidf, X_test_tfidf_svd
    # bst = xgb.XGBClassifier()
    # bst = bst.load_model('save_model_xgb.json')
    X_test_tfidf = tfidf_vect.transform(X_test)
    X_test_tfidf_svd = svd.transform(X_test_tfidf)
    test_predictions = bst.predict(X_test_tfidf_svd)
    print(test_predictions)
    return test_predictions

app = Flask(__name__)


# run_with_ngrok(app)   #starts ngrok when the app is run

@app.route("/ping")
def test(request):
    return json({"hello": "world"})


@app.route("/", methods=['GET'])
def home():
    return jsonify(classify(X_test).tolist())


if __name__ == '__main__':
    app.run()
    # for i in range(100):
    #     print(classify("hom na
    #     y em di chua huong"))